server:
  port: 8007

springdoc:
  enable-spring-security: false

laa:
  ccms:
    soa-gateway:
      username: soa-user
      password: soa-password
      notification:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/NotificationService
        service-url: http://localhost:8051/soa-infra/services/default/NotificationServices/NotificationServices_ep
      contract-details:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: http://localhost:8051/soa-infra/services/default/GetContractDetails/getcontractdetails_ep
      client:
        service-name: http://legalservices.gov.uk/CCMS/ClientManagement/Client/1.0/ClientServices
        service-url: http://localhost:8051/soa-infra/services/default/ClientServices/ClientServices_ep
      reference-data:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: http://localhost:8051/soa-infra/services/default/GetReferenceData/getreferencedata_ep
      case:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices
        service-url: http://localhost:8051/soa-infra/services/default/CaseServices/CaseServices_ep
      provider-request:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/SubmitProviderRequest
        service-url: http://localhost:8051/soa-infra/services/default/SubmitProviderRequest/submitproviderrequest_ep
      document:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/DocumentServices
        service-url:  http://localhost:8051/soa-infra/services/default/DocumentServices/DocumentServices_ep
      commonorg:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/ReferenceDataBIM
        service-url: http://localhost:8051/soa-infra/services/default/GetCommonOrg/getcommonorg_ep
      cover-sheet:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/GetCoverSheet
        service-url: http://localhost:8051/soa-infra/services/default/GetCoverSheet/getcoversheet_ep
      user:
        service-name: http://legalaid.gsi.gov.uk/CCMS/Common/UserManagement/1.0/UserManagementBIM
        service-url: http://localhost:8051/soa-infra/services/default/UpdateUser/UpdateUser_ep
    springboot.starter.auth:
      authentication-header: "Authorization"
      authorized-clients: '[
          {
              "name": "integration-test-runner",
              "roles": [
                  "ALL"
              ],
              "token": "94549740-5aaa-4cd9-b9d9-666159d268a9"
          }
      ]'
      authorized-roles: '[
          {
              "name": "ALL",
              "URIs": [
                  "/**"
              ]
          }
      ]'
      unprotected-uris: [ "/swagger-ui.html", "/swagger-ui/**", "/v3/api-docs/**", "/favicon.ico", "/open-api-specification.yml" ]
