springdoc:
  enable-spring-security: false

laa:
  ccms:
    soa-gateway:
      username: ${SOA_GATEWAY_USERNAME}
      password: ${SOA_GATEWAY_PASSWORD}
      notification:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/NotificationService
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/NotificationServices/NotificationServices_ep
      contract-details:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/GetContractDetails/getcontractdetails_ep
      client:
        service-name: http://legalservices.gov.uk/CCMS/ClientManagement/Client/1.0/ClientServices
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/ClientServices/ClientServices_ep
      reference-data:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/GetReferenceData/getreferencedata_ep
      case:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/CaseServices/CaseServices_ep
      provider-request:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/SubmitProviderRequest
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/SubmitProviderRequest/submitproviderrequest_ep
      document:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/DocumentServices
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/DocumentServices/DocumentServices_ep
      commonorg:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/ReferenceDataBIM
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/GetCommonOrg/getcommonorg_ep
      cover-sheet:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/GetCoverSheet
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/GetCoverSheet/getcoversheet_ep
      user:
        service-name: http://legalaid.gsi.gov.uk/CCMS/Common/UserManagement/1.0/UserManagementBIM
        service-url: ${SOA_SERVICE_URL}/soa-infra/services/default/UpdateUser/UpdateUser_ep
    springboot:
      starter:
        auth:
          authentication-header: "Authorization"
          authorized-clients: ${AUTHORIZED_CLIENTS}
          authorized-roles: ${AUTHORIZED_ROLES}
          unprotected-uris: ${UNPROTECTED_URIS}
