server:
  port: 8007

laa:
  ccms:
    soa-gateway:
      username: pui_user
      password: THj9f52dH2NV
      notification:
        service-name: ${NOTIFICATIONS_SERVICE_NAME}
        service-url: ${NOTIFICATIONS_SERVICE_URL}
      contract-details:
        service-name: ${CONTRACT_DETAILS_SERVICE_NAME}
        service-url: ${CONTRACT_DETAILS_SERVICE_URL}
      client:
        service-name: ${CLIENT_SERVICE_NAME}
        service-url: ${CLIENT_SERVICE_URL}
      reference-data:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: http://localhost:8051/soa-infra/services/default/GetReferenceData/getreferencedata_ep
      case:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/CaseServices
        service-url: http://localhost:8051/soa-infra/services/default/CaseServices/CaseServices_ep

