server:
  port: 8007

laa:
  ccms:
    soa-gateway:
      username: ${SOA_GATEWAY_USERNAME}
      password: ${SOA_GATEWAY_PASSWORD}
      notification:
        service-name: ${NOTIFICATIONS_SERVICE_NAME}
        service-url: ${NOTIFICATIONS_SERVICE_URL}
      contract-details:
        service-name: ${CONTRACT_DETAILS_SERVICE_NAME}
        service-url: ${CONTRACT_DETAILS_SERVICE_URL}
      client:
        service-name: ${CLIENT_SERVICE_NAME}
        service-url: ${CLIENT_SERVICE_URL}
      reference-data:
        service-name: ${REFERENCE_DATA_SERVICE_NAME}
        service-url: ${REFERENCE_DATA_SERVICE_URL}
      case:
        service-name: ${CASE_SERVICE_NAME}
        service-url: ${CASE_SERVICE_URL}

