laa:
  ccms:
    soa-gateway:
      username: pui_user
      password: THj9f52dH2NV
      notification:
        service-name: http://legalservices.gov.uk/CCMS/CaseManagement/Case/1.0/NotificationService
        service-url: http://localhost:8051/soa-infra/services/default/NotificationServices/NotificationServices_ep
      contract-details:
        service-name: http://legalservices.gov.uk/CCMS/Common/ReferenceData/1.0/GetReferenceData
        service-url: http://localhost:8051/soa-infra/services/default/GetReferenceData/ContractDetailsService_ep