# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  packages: write

jobs:
    build-test-publish:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Build with Gradle
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: build
        - name: upload jarfile
          uses: actions/upload-artifact@v3
          with:
            name: soa-jar
            path: build/libs/laa-ccms-soa-gateway-api-0.0.1-SNAPSHOT.jar

        - name: Test
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: jacocoTestCoverageVerification

        - name: Integration Test
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: integrationTest

        - name: Update snapshot version
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: updateSnapshotVersion

        - name: Publish package
          uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
          with:
            arguments: publish
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ecr:
      needs: build-test-publish
      runs-on: ubuntu-latest
      permissions:
        id-token: write # for requesting jwt
        contents: read  # for actions/checkout
      steps:
        # Checkout github repo
        - uses: actions/checkout@v3
        # Assume role in cloud platform
        - name: download jar
          uses: actions/download-artifact@v3
          with:
            name: soa-jar
        - name: display structure of downloaded files
          run: ls -R
